using CCS.Modules.Inventory;

// =============================================================================
// SCRIPT: CCS_WildlifeHarvestedItemDrop
// CATEGORY: Modules / Wildlife / Runtime / Data
// PURPOSE: Runtime drop payload generated by wildlife harvest service.
// PLACEMENT: Returned inside CCS_WildlifeHarvestResult.
// AUTHOR: James Schilz
// CREATED: 2026-06-01
// NOTES: Not a ScriptableObject drop definition.
// =============================================================================

namespace CCS.Modules.Wildlife
{
    public sealed class CCS_WildlifeHarvestedItemDrop
    {
        #region Public Methods

        public CCS_WildlifeHarvestedItemDrop(CCS_ItemDefinition itemDefinition, int quantity)
        {
            ItemDefinition = itemDefinition;
            Quantity = quantity < 0 ? 0 : quantity;
        }

        #endregion

        #region Properties

        public CCS_ItemDefinition ItemDefinition { get; }

        public int Quantity { get; }

        #endregion
    }
}
